---
version: "3"
services:
  nginx:
    image: "workshop_nginx"
    build:
      context: nginx
    ports:
      - "8000:80"
  client:
    image: "workshop_client"
    build:
      context: client
    command: npm start
    volumes:
      - ./client:/app
  server:
    image: "workshop_server"
    build:
      context: server
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: server
      POSTGRES_DB: barbershop
      POSTGRES_PASSWORD: top_secret
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
